### ISSUE TITLE
Tag for ss5 compatible changes

### ISSUE THREAD

**Issue by dizzystuff** [tractorcow/silverstripe-image-formatter#4]
Hi! Would you mind please creating a new tag/release with the merged ss5-compat composer changes?

**Comment by tractorcow** [comment]
https://github.com/tractorcow/silverstripe-image-formatter/releases/tag/1.1.0 thanks and sorry for missing the alerts :)

**Comment by dizzystuff** [comment]
All good, thanks for that!
